from __future__ import annotations

from pathlib import Path

from .common import Error, digest, load_json, load_yaml, lock, safe_path, utcnow, write_json, write_yaml
from .core import validate_config, validate_knowledge


def prepare_candidates(root: Path, task: dict, response: dict) -> list[dict]:
    config = load_yaml(safe_path(root, ".review/config.yaml"))
    validate_config(config)
    if not isinstance(task, dict) or task.get("task_type") != "induce":
        raise Error("Expected an induction task generated by bootstrap/harvest.")
    if task.get("repository") != config["repository"]:
        raise Error("Task repository does not match initialized repository.")
    if not isinstance(task.get("input"), dict) or digest(task["input"]) != task.get("input_hash"):
        raise Error("Induction task input hash is invalid.")
    if task["input"].get("evidence") != task.get("evidence"):
        raise Error("Task evidence differs from its hashed input.")
    if not isinstance(response, dict) or any(response.get(key) != task.get(key) or not task.get(key)
                                             for key in ("task_id", "input_hash")):
        raise Error("Response task_id/input_hash does not match the induction task.")
    model = response.get("model")
    if not isinstance(model, dict) or any(not isinstance(model.get(key), str) or not model[key].strip()
                                          for key in ("provider", "model", "prompt_version")):
        raise Error("Response requires model.provider, model.model and model.prompt_version (unknown when unavailable).")
    if model["provider"] != config["model_provider"]:
        raise Error("Response provider is not the explicitly configured provider.")
    evidence = task.get("evidence")
    if not isinstance(evidence, list):
        raise Error("Induction task has no evidence list.")
    by_id = {}
    for reference in evidence:
        if not isinstance(reference, dict):
            raise Error("Invalid evidence bundle.")
        if "path" in reference:
            path = safe_path(root, reference["path"])
            if not path.is_relative_to(safe_path(root, ".review/local/raw/evidence")):
                raise Error("Evidence references must stay in the local raw evidence directory.")
            bundle = load_json(path)
            if digest(bundle) != reference.get("content_hash"):
                raise Error("Evidence content changed after the task was prepared.")
            if bundle.get("evidence_id") != reference.get("evidence_id"):
                raise Error("Evidence ID does not match the task reference.")
        else:
            bundle = reference
        key = bundle.get("evidence_id") or bundle.get("bundle_id") or bundle.get("id")
        if not isinstance(key, str) or key in by_id:
            raise Error("Evidence IDs must be unique nonempty strings.")
        if bundle.get("repository") != task["repository"] or type(bundle.get("pr")) is not int:
            raise Error("Evidence repository or PR identity is invalid.")
        by_id[key] = bundle
    candidates = response.get("candidates")
    if not isinstance(candidates, list):
        raise Error("Response candidates must be a list; an empty list is a valid negative result.")
    prepared = []
    ids = set()
    for item in candidates:
        if not isinstance(item, dict):
            raise Error("Candidate must be an object.")
        item = dict(item)
        if item.get("maturity") not in {"candidate", "lesson"}:
            raise Error("Induction cannot approve knowledge.")
        validate_knowledge(item)
        references = item.pop("evidence_ids", None)
        if not isinstance(references, list) or not references or any(ref not in by_id for ref in references):
            raise Error("Each candidate must cite evidence_ids from this task.")
        if len(set(references)) != len(references):
            raise Error("Duplicate evidence IDs do not count as independent support.")
        for source in item.get("sources", []):
            if source.get("kind") == "history" and source.get("reference") not in references:
                raise Error("Historical sources must reference this candidate's evidence IDs.")
        non_history = [s for s in item.get("sources", []) if s.get("kind") != "history"]
        item["sources"] = non_history + [
            {"kind": "history", "reference": ref, "version": digest(by_id[ref]),
             "available_at": by_id[ref].get("available_at") or by_id[ref].get("timestamps", {}).get("observed_at") or task.get("created_at") or utcnow()}
            for ref in references
        ]
        validate_knowledge(item)
        if item["id"] in ids:
            raise Error("A response cannot define multiple revisions of the same knowledge ID.")
        ids.add(item["id"])
        prs = {(by_id[ref].get("repository"), by_id[ref].get("pr")) for ref in references}
        prepared.append({"knowledge": item, "evidence_ids": references,
                         "observed_pr_count": len(prs), "independence": "unverified",
                         "adjudication": "unjudged"})
    return prepared


def propose(root: Path, task_path: Path, response_path: Path) -> dict:
    task, response = load_json(task_path), load_json(response_path)
    prepared = prepare_candidates(root, task, response)
    model = response["model"]
    response_hash = digest(response)
    key = digest({"task": task, "response": response})
    directory = safe_path(root, f".review/local/proposals/{key}")
    with lock(root):
        manifest = directory / "proposal.json"
        if manifest.exists():
            return {"status": "already_proposed", "proposal": str(manifest),
                    "candidate_count": len(prepared)}
        for row in prepared:
            item = row["knowledge"]
            write_yaml(directory / f"{item['id']}-r{item['revision']}.yaml", item)
        write_json(directory / "task.json", task)
        write_json(directory / "response.json", response)
        write_json(manifest, {
            "schema_version": 1, "task_id": task["task_id"], "input_hash": task["input_hash"],
            "response_hash": response_hash, "model": model, "created_at": utcnow(),
            "candidates": prepared, "coverage_gaps": task.get("coverage_gaps", task.get("gaps", [])),
            "cost": {"induction_tokens": None, "clustering_tokens": None, "cache_reused": False},
            "status": "awaiting_evidence_review_and_approval",
        })
    return {"status": "proposed", "proposal": str(directory / "proposal.json"),
            "candidate_count": len(prepared)}
